name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Delete Docker Container
      run: docker compose -f ./docker/be.docker-compose.yml down
    - name: Clean Docker Image
      run: docker rmi -f yosefadi/capstone_be:latest
    - name: Run Docker Container
      run: docker compose -f ./docker/be.docker-compose.yml up -d
      env:
        TOKEN_WA: ${{ secrets.TOKEN_WA }}
        MQTT_USER: ${{ secrets.MQTT_USER }}
        MQTT_PASS: ${{ secrets.MQTT_PASS }}
        PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
        PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
        PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
        PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}
